<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>Launcher</AssemblyName>
    <RootNamespace>NYCLauncher</RootNamespace>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Optimize Condition="'$(Configuration)'=='Release'">true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Downloader" Version="3.1.2" />
    <PackageReference Include="K4os.Hash.xxHash" Version="1.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\logo_wide.png" />
    <Resource Include="Assets\skyline.png" />
    <Resource Include="Assets\Fonts\Geist-Regular.ttf" />
    <Resource Include="Assets\Fonts\Geist-Medium.ttf" />
    <Resource Include="Assets\Fonts\Geist-SemiBold.ttf" />
    <Resource Include="Assets\Fonts\Geist-Bold.ttf" />
    <Resource Include="Assets\Fonts\GeistMono-Regular.ttf" />
    <Resource Include="Assets\Fonts\GeistMono-Medium.ttf" />
    <Resource Include="Assets\Fonts\DrukWide-Bold.ttf" />
  </ItemGroup>

</Project>
